import*as THREE from'https://unpkg.com/three@0.160.0/build/three.module.js';
import{OrbitControls}from'https://unpkg.com/three@0.160.0/examples/jsm/controls/OrbitControls.js';
import{distance3,rewardStep,targetForEpisode,successRate,ACTIONS}from'./lib/drone-core.mjs';

const $=id=>document.getElementById(id),world=$('viewport'),brainCanvas=$('brain'),chartCanvas=$('chart');
const state={running:true,speed:3,difficulty:'normal',episode:Number(localStorage.getItem('fly-drone-episode')||0),reward:0,lastStepReward:0,collisions:0,successHistory:JSON.parse(localStorage.getItem('fly-drone-success')||'[]'),curve:JSON.parse(localStorage.getItem('fly-drone-curve')||'[]'),battery:1,time:0,step:0,missionTime:0,seed:381};
const drone={p:new THREE.Vector3(0,3,0),v:new THREE.Vector3(),yaw:0,target:new THREE.Vector3(),collision:false};
const scene=new THREE.Scene();scene.background=new THREE.Color('#080c10');scene.fog=new THREE.Fog('#080c10',32,105);
const camera=new THREE.PerspectiveCamera(54,1,.1,200);camera.position.set(9,8,13);
let renderer,renderSurface,fallbackCtx;try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderSurface=renderer.domElement;world.append(renderSurface)}catch{renderSurface=document.createElement('canvas');renderSurface.className='fallback-canvas';fallbackCtx=renderSurface.getContext('2d');world.append(renderSurface)}
const controls=new OrbitControls(camera,renderSurface);controls.enableDamping=true;controls.enablePan=false;controls.target.set(0,2,0);controls.maxPolarAngle=Math.PI*.47;controls.minDistance=7;controls.maxDistance=36;controls.enabled=false;
scene.add(new THREE.HemisphereLight('#c3e8ff','#192127',2));const sun=new THREE.DirectionalLight('#d7f6ff',3);sun.position.set(8,18,6);scene.add(sun);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(130,130),new THREE.MeshStandardMaterial({color:'#0d1419',roughness:.9,metalness:.1}));floor.rotation.x=-Math.PI/2;scene.add(floor);
const grid=new THREE.GridHelper(130,65,'#22313a','#101a20');grid.position.y=.01;grid.material.transparent=true;grid.material.opacity=.45;scene.add(grid);
const droneGroup=new THREE.Group();scene.add(droneGroup);
const body=new THREE.Mesh(new THREE.BoxGeometry(1.35,.28,.72),new THREE.MeshStandardMaterial({color:'#17232a',metalness:.8,roughness:.26}));droneGroup.add(body);
const nose=new THREE.Mesh(new THREE.BoxGeometry(.18,.12,.52),new THREE.MeshStandardMaterial({color:'#bdff38',emissive:'#426900',emissiveIntensity:1.2}));nose.position.set(.7,.02,0);droneGroup.add(nose);
const armMat=new THREE.MeshStandardMaterial({color:'#7a8b94',metalness:.9,roughness:.25});
for(const z of[-.62,.62])for(const x of[-.52,.52]){const arm=new THREE.Mesh(new THREE.BoxGeometry(.9,.1,.1),armMat);arm.position.set(x,0,z);arm.rotation.y=x*z>0?-.5:.5;droneGroup.add(arm);const prop=new THREE.Mesh(new THREE.TorusGeometry(.38,.025,6,28),new THREE.MeshBasicMaterial({color:'#bdff38',transparent:true,opacity:.72}));prop.rotation.x=Math.PI/2;prop.position.set(x*1.18,.06,z*1.18);droneGroup.add(prop)}
const beacon=new THREE.Group();const beaconCore=new THREE.Mesh(new THREE.IcosahedronGeometry(.55,2),new THREE.MeshBasicMaterial({color:'#bdff38',emissive:'#bdff38',emissiveIntensity:2}));beacon.add(beaconCore);const beaconRing=new THREE.Mesh(new THREE.TorusGeometry(1.05,.025,8,48),new THREE.MeshBasicMaterial({color:'#bdff38',transparent:true,opacity:.65}));beaconRing.rotation.x=Math.PI/2;beacon.add(beaconRing);scene.add(beacon);
let obstacles=[];const obstacleGroup=new THREE.Group();scene.add(obstacleGroup);
function makeObstacle(x,z,w,d,h){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color:'#17242c',roughness:.65,metalness:.2}));mesh.position.set(x,h/2,z);obstacleGroup.add(mesh);obstacles.push({mesh,x,z,w,d,h})}
function populate(){obstacles=[];while(obstacleGroup.children.length)obstacleGroup.remove(obstacleGroup.children[0]);const count=state.difficulty==='easy'?5:state.difficulty==='hard'?18:11;for(let i=0;i<count;i++){const a=i*2.399+state.episode*.17,r=5+(i*7%17);makeObstacle(Math.cos(a)*r,Math.sin(a)*r,1.5+(i%3)*.7,1.5+(i%2)*.8,2.5+(i%5)*1.6)}}
const sensorGroup=new THREE.Group();scene.add(sensorGroup);const sensorLines=[];for(let i=0;i<6;i++){const mat=new THREE.LineBasicMaterial({color:'#62dfff',transparent:true,opacity:.22});const geo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3(0,0,1)]);const line=new THREE.Line(geo,mat);sensorGroup.add(line);sensorLines.push(line)}
const brainCtx=brainCanvas.getContext('2d'),chartCtx=chartCanvas.getContext('2d');let brainNodes=[];function fit(){const r=world.getBoundingClientRect();if(renderer)renderer.setSize(r.width,r.height,false);else{const d=Math.min(devicePixelRatio,2);renderSurface.width=r.width*d;renderSurface.height=r.height*d;fallbackCtx.setTransform(d,0,0,d,0,0)}camera.aspect=r.width/r.height;camera.updateProjectionMatrix();const br=brainCanvas.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);brainCanvas.width=br.width*d;brainCanvas.height=br.height*d;brainCtx.setTransform(d,0,0,d,0,0);const cr=chartCanvas.getBoundingClientRect();chartCanvas.width=cr.width*d;chartCanvas.height=cr.height*d;chartCtx.setTransform(d,0,0,d,0,0)}
function resetMission(){state.episode++;state.reward=0;state.lastStepReward=0;state.collisions=0;state.battery=1;state.time=0;state.step=0;state.missionTime=0;state.seed=(state.episode*104729+7919)>>>0;const t=targetForEpisode(state.episode,state.difficulty==='hard'?25:20);drone.target.set(t.x,t.y,t.z);beacon.position.copy(drone.target);drone.p.set(0,3,0);drone.v.set(0,0,0);drone.yaw=0;drone.collision=false;populate();$('episode').textContent=state.episode.toLocaleString();$('phase').textContent=state.episode%10===0?'TEST':'TRAIN';$('seed').textContent=state.seed;log('Mission reset · seed_'+state.seed);localStorage.setItem('fly-drone-episode',state.episode)}
function features(){const dx=drone.target.x-drone.p.x,dy=drone.target.y-drone.p.y,dz=drone.target.z-drone.p.z,dist=Math.max(1,Math.hypot(dx,dy,dz));const bearing=Math.atan2(dz,dx),angle=Math.atan2(Math.sin(bearing-drone.yaw),Math.cos(bearing-drone.yaw));const f=[(dx/24+1)/2,(dy/12+1)/2,(dz/24+1)/2,(Math.sin(angle)+1)/2,(Math.cos(angle)+1)/2,Math.min(1,Math.hypot(drone.v.x,drone.v.z)/3),drone.v.y>0?.7:.3,state.battery,...lidar(),state.collisions?1:0];return f.slice(0,18)}
function lidar(){return sensorLines.map((line,i)=>{const a=drone.yaw+(i-2.5)*Math.PI/5,dx=Math.cos(a),dz=Math.sin(a);let hit=12;for(const o of obstacles){const nearX=Math.abs(o.x-drone.p.x-dx*3),nearZ=Math.abs(o.z-drone.p.z-dz*3);if(nearX<o.w/2+2&&nearZ<o.d/2+2)hit=Math.min(hit,Math.max(.6,Math.hypot(o.x-drone.p.x,o.z-drone.p.z)-Math.max(o.w,o.d)/2))}const points=line.geometry.attributes.position;points.setXYZ(0,drone.p.x,drone.p.y,drone.p.z);points.setXYZ(1,drone.p.x+dx*hit,drone.p.y,drone.p.z+dz*hit);points.needsUpdate=true;line.material.color.setHex(hit<2?'0xff5b67':'0x62dfff');return Math.min(1,hit/12)})}
function teacher(){const dx=drone.target.x-drone.p.x,dz=drone.target.z-drone.p.z,bearing=Math.atan2(dz,dx),a=Math.atan2(Math.sin(bearing-drone.yaw),Math.cos(bearing-drone.yaw));if(lidar().some(x=>x<.18))return 3;if(Math.abs(a)>.27)return a<0?1:2;if(drone.target.y-drone.p.y>.8)return 3;if(drone.target.y-drone.p.y<-.8)return 4;return 0}
function applyAction(action,dt){const thrust=state.difficulty==='hard'?2.3:2.8;const forward=new THREE.Vector3(Math.cos(drone.yaw),0,Math.sin(drone.yaw));if(action===0)drone.v.addScaledVector(forward,thrust*dt);if(action===1)drone.yaw+=1.8*dt;if(action===2)drone.yaw-=1.8*dt;if(action===3)drone.v.y+=thrust*.75*dt;if(action===4)drone.v.y-=thrust*.75*dt;drone.v.multiplyScalar(Math.pow(.91,dt*60));drone.v.y-=.35*dt;drone.p.addScaledVector(drone.v,dt);drone.p.y=Math.max(.55,Math.min(12,drone.p.y));droneGroup.position.copy(drone.p);droneGroup.rotation.y=-drone.yaw;droneGroup.rotation.z=-drone.v.x*.025}
function checkCollision(){drone.collision=false;if(drone.p.y<.7){drone.collision=true;drone.p.y=.7;drone.v.multiplyScalar(-.25)}for(const o of obstacles)if(Math.abs(drone.p.x-o.x)<o.w/2+.65&&Math.abs(drone.p.z-o.z)<o.d/2+.65&&drone.p.y<o.h+.5){drone.collision=true;drone.v.multiplyScalar(-.35);state.collisions++}return drone.collision}
function updateUI(data){$('action').textContent=ACTIONS[data.action];$('motorOutput').textContent=ACTIONS[data.action];$('confidence').textContent='confidence '+Math.round(Math.max(...data.probs)*100)+'%';$('spikeRate').textContent=(data.spikes*100).toLocaleString()+' spikes/s';$('updates').textContent=data.updates.toLocaleString();$('meanDelta').textContent='mean Δ '+data.meanDelta.toFixed(6);for(let i=0;i<6;i++)$('p'+i).style.width=Math.max(5,data.probs[i]*100)+'%';$('collisions').textContent=state.collisions;$('battery').textContent=Math.round(state.battery*100)+'%';$('altitude').textContent='altitude '+drone.p.y.toFixed(1)+' m';const d=distance3(drone.p,drone.target);$('distance').textContent=d.toFixed(1)+' m';$('bearing').textContent='bearing '+Math.round(THREE.MathUtils.radToDeg(Math.atan2(drone.target.z-drone.p.z,drone.target.x-drone.p.x)-drone.yaw))+'°';drawBrain(data);}
function drawBrain(data){const r=brainCanvas.getBoundingClientRect(),w=r.width,h=r.height;brainCtx.clearRect(0,0,w,h);if(!brainNodes.length)brainNodes=Array.from({length:110},(_,i)=>({x:Math.random()*w,y:Math.random()*h,layer:i<18?0:i>96?2:1}));brainCtx.lineWidth=.45;for(let i=0;i<brainNodes.length;i++){const a=brainNodes[i];for(let j=1;j<3;j++){const b=brainNodes[(i*17+j*31)%brainNodes.length];brainCtx.strokeStyle=data.active.includes(i)?'#bdff3850':'#6b879318';brainCtx.beginPath();brainCtx.moveTo(a.x,a.y);brainCtx.lineTo(b.x,b.y);brainCtx.stroke()}}brainNodes.forEach((n,i)=>{const on=data.active.includes(i),r=on?1.7+(i%3):.8;brainCtx.fillStyle=on?(n.layer===0?'#62dfff':n.layer===2?'#bdff38':'#a1aeb6'):'#49616d55';brainCtx.beginPath();brainCtx.arc(n.x,n.y,r,0,Math.PI*2);brainCtx.fill()})}
function drawChart(){const r=chartCanvas.getBoundingClientRect(),w=r.width,h=r.height;chartCtx.clearRect(0,0,w,h);const vals=state.curve.slice(-100);if(vals.length<2)return;chartCtx.strokeStyle='#bdff38';chartCtx.lineWidth=1.5;chartCtx.beginPath();vals.forEach((v,i)=>{const x=i/(vals.length-1)*w,y=h-(v*.8+.1)*h;i?chartCtx.lineTo(x,y):chartCtx.moveTo(x,y)});chartCtx.stroke()}
function drawFallback(){const r=world.getBoundingClientRect(),w=r.width,h=r.height;fallbackCtx.clearRect(0,0,w,h);fallbackCtx.fillStyle='#0d151b';fallbackCtx.fillRect(0,0,w,h);const horizon=h*.42;fallbackCtx.strokeStyle='#1c3039';fallbackCtx.lineWidth=1;for(let i=-12;i<=12;i++){const x=w/2+i*42;fallbackCtx.beginPath();fallbackCtx.moveTo(w/2+(x-w/2)*.22,horizon);fallbackCtx.lineTo(x,h);fallbackCtx.stroke()}for(let i=0;i<9;i++){const y=horizon+i*i*7;fallbackCtx.beginPath();fallbackCtx.moveTo(0,y);fallbackCtx.lineTo(w,y);fallbackCtx.stroke()}const project=(x,z,y=0)=>({x:w/2+x*18/(1+Math.max(0,y)*.03),y:h*.7+z*14/(1+Math.max(0,y)*.03)-y*15});obstacles.forEach(o=>{const q=project(o.x,o.z,o.h/2);fallbackCtx.fillStyle='#243943';fallbackCtx.fillRect(q.x-o.w*7,q.y-o.h*7,o.w*14,o.h*14)});const b=project(drone.target.x,drone.target.z,drone.target.y);fallbackCtx.strokeStyle='#bdff38';fallbackCtx.globalAlpha=.55;fallbackCtx.beginPath();fallbackCtx.arc(b.x,b.y,22,0,Math.PI*2);fallbackCtx.stroke();fallbackCtx.globalAlpha=1;fallbackCtx.fillStyle='#bdff38';fallbackCtx.beginPath();fallbackCtx.arc(b.x,b.y,7,0,Math.PI*2);fallbackCtx.fill();const d=project(drone.p.x,drone.p.z,drone.p.y);fallbackCtx.save();fallbackCtx.translate(d.x,d.y);fallbackCtx.rotate(-drone.yaw);fallbackCtx.fillStyle='#dfe8eb';fallbackCtx.fillRect(-18,-5,36,10);fallbackCtx.strokeStyle='#bdff38';fallbackCtx.strokeRect(-18,-5,36,10);fallbackCtx.restore();fallbackCtx.fillStyle='#71808a';fallbackCtx.font='10px ui-monospace,monospace';fallbackCtx.fillText('WEBGL UNAVAILABLE · 2D TELEMETRY FALLBACK',16,28)}
function log(text){const p=document.createElement('p');p.innerHTML='<time>'+new Date().toISOString().slice(11,19)+'</time>'+text;$('eventLog').prepend(p);while($('eventLog').children.length>5)$('eventLog').lastChild.remove()}
let pendingAction=5,lastDistance=0,decisionClock=0;const worker=new Worker('drone-brain-worker.js?v=1');worker.onmessage=({data})=>{if(data.type==='ready'){const checkpoint=JSON.parse(localStorage.getItem('fly-drone-checkpoint')||'null');if(checkpoint)worker.postMessage({type:'restore',data:checkpoint});return}if(data.type==='restored'){$('updates').textContent=data.updates.toLocaleString();return}if(data.type==='checkpoint'){localStorage.setItem('fly-drone-checkpoint',JSON.stringify(data.data));return}if(data.type==='decision'){pendingAction=data.action;updateUI(data)}};worker.postMessage({type:'init',seed:381});
function endMission(success){state.successHistory.push(success);state.successHistory=state.successHistory.slice(-500);state.curve.push(successRate(state.successHistory));state.curve=state.curve.slice(-100);localStorage.setItem('fly-drone-success',JSON.stringify(state.successHistory));localStorage.setItem('fly-drone-curve',JSON.stringify(state.curve));worker.postMessage({type:'checkpoint'});log(success?'✓ Beacon reached · reward +2.0':'× Mission timeout · reward −0.8');setTimeout(resetMission,650)}
function tick(dt){if(!state.running)return;state.time+=dt*state.speed;state.missionTime+=dt*state.speed;decisionClock+=dt*state.speed;const previous=distance3(drone.p,drone.target);if(decisionClock>.12){worker.postMessage({type:'step',features:features(),reward:state.lastStepReward,train:state.episode%10!==0,teacher:teacher()});decisionClock=0}applyAction(pendingAction,dt*state.speed*.35);const collision=checkCollision(),d=distance3(drone.p,drone.target);state.battery=Math.max(0,state.battery-dt*.0008);state.lastStepReward=(d<1.1?2:0)+(previous-d)*.12-(collision?.8:0)-.001;state.reward+=state.lastStepReward;state.step++;if(d<1.1){endMission(true);return}if(state.missionTime>26||state.battery<=0){endMission(false);return}droneGroup.position.copy(drone.p);beaconCore.rotation.y+=dt;beaconRing.rotation.z+=dt*.7;lastDistance=d;$('reward').textContent=state.reward.toFixed(3);$('success').textContent=(successRate(state.successHistory)*100).toFixed(1)+'%';}
let previousTime=performance.now();function animate(now){const dt=Math.min(.05,(now-previousTime)/1000);previousTime=now;tick(dt);if($('cameraLabel').textContent==='CHASE CAMERA'){const offset=new THREE.Vector3(-Math.cos(drone.yaw)*8,4.8,-Math.sin(drone.yaw)*8);camera.position.lerp(drone.p.clone().add(offset),.06);controls.target.lerp(drone.p,.08)}controls.update();if(renderer)renderer.render(scene,camera);else drawFallback();requestAnimationFrame(animate)}
$('toggle').onclick=()=>{state.running=!state.running;$('toggle').innerHTML=state.running?'Ⅱ&nbsp;&nbsp; PAUSE':'▶&nbsp;&nbsp; RESUME';$('runStatus').textContent=state.running?'AUTONOMY ONLINE':'TRAINING PAUSED'};$('reset').onclick=resetMission;$('speed').oninput=e=>{state.speed=+e.target.value;$('speedOut').textContent=state.speed+'×'};$('difficulty').onchange=e=>{state.difficulty=e.target.value;resetMission()};document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-camera]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const mode=b.dataset.camera;if(mode==='orbit'){controls.enabled=true;$('cameraLabel').textContent='ORBIT CAMERA'}else{controls.enabled=false;$('cameraLabel').textContent=mode==='top'?'MAP CAMERA':'CHASE CAMERA';if(mode==='top'){camera.position.set(0,31,.1);controls.enabled=true;controls.target.copy(drone.p)}}});addEventListener('resize',fit);fit();resetMission();drawChart();requestAnimationFrame(animate);
