const $=id=>document.getElementById(id),state={running:true,speed:3,episode:20148,reward:.7488,success:72.4,steps:18.6,seed:381,t:0,history:Array.from({length:46},(_,i)=>.25+i*.009+Math.random()*.09)};
const els={brain:$('brain'),chart:$('chart'),cursor:$('cursor'),agent:$('agentCursor'),target:$('target'),log:$('eventLog')};
const ctx=els.brain.getContext('2d'),chartCtx=els.chart.getContext('2d');
let nodes=[],target={x:68,y:32},agent={x:20,y:70},last=0,episodeTimer=0;
function resize(canvas,context){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);canvas.width=r.width*d;canvas.height=r.height*d;context.setTransform(d,0,0,d,0,0)}
function initBrain(){resize(els.brain,ctx);const {width:w,height:h}=els.brain.getBoundingClientRect();nodes=Array.from({length:145},(_,i)=>{const a=Math.random()*Math.PI*2,r=Math.pow(Math.random(),.64)*Math.min(w,h)*.42;return{x:w/2+Math.cos(a)*r*(1+.45*Math.sin(a)),y:h/2+Math.sin(a)*r,z:Math.random(),p:Math.random()*6.28,n:i}})}
function drawBrain(t){const {width:w,height:h}=els.brain.getBoundingClientRect();ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(w/2,h/2);ctx.rotate(Math.sin(t*.00012)*.05);ctx.translate(-w/2,-h/2);ctx.lineWidth=.45;for(let i=0;i<nodes.length;i++){const a=nodes[i];for(let j=1;j<3;j++){const b=nodes[(i*17+j*31)%nodes.length],d=Math.hypot(a.x-b.x,a.y-b.y);if(d<115){const active=Math.sin(t*.006+a.p+i)>.82;ctx.strokeStyle=active?'rgba(199,255,61,.48)':'rgba(84,135,157,.09)';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}}nodes.forEach((n,i)=>{const active=Math.sin(t*.008*state.speed+n.p+i*.19)>.72,r=active?1.8+n.z*2:.5+n.z;ctx.fillStyle=active?(i%9?'#bdf7ff':'#c7ff3d'):`rgba(93,151,170,${.18+n.z*.22})`;ctx.beginPath();ctx.arc(n.x+Math.sin(t*.0004+n.p)*3,n.y+Math.cos(t*.0003+n.p)*2,r,0,7);ctx.fill()});ctx.restore()}
function drawChart(){resize(els.chart,chartCtx);const {width:w,height:h}=els.chart.getBoundingClientRect();chartCtx.clearRect(0,0,w,h);chartCtx.strokeStyle='#c7ff3d';chartCtx.lineWidth=1.5;chartCtx.beginPath();state.history.forEach((v,i)=>{const x=i/(state.history.length-1)*w,y=h-v*h*.88;(i?chartCtx.lineTo(x,y):chartCtx.moveTo(x,y))});chartCtx.stroke();const g=chartCtx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#c7ff3d22');g.addColorStop(1,'#c7ff3d00');chartCtx.lineTo(w,h);chartCtx.lineTo(0,h);chartCtx.fillStyle=g;chartCtx.fill()}
function log(text){const p=document.createElement('p');p.innerHTML=`<time>${new Date().toISOString().slice(14,23)}</time>${text}`;els.log.prepend(p);while(els.log.children.length>4)els.log.lastChild.remove()}
function resetWorld(){target={x:12+Math.random()*72,y:12+Math.random()*58};agent={x:12+Math.random()*70,y:15+Math.random()*60};els.target.style.left=target.x+'%';els.target.style.top=target.y+'%';state.seed=Math.floor(Math.random()*9000);$('seed').textContent=state.seed;log(`Environment reset · seed_${state.seed}`)}
function step(dt){if(!state.running)return;state.t+=dt*state.speed;episodeTimer+=dt*state.speed;const dx=target.x-agent.x,dy=target.y-agent.y,d=Math.hypot(dx,dy);const skill=.22+state.success/125;agent.x+=dx*Math.min(.025*state.speed*skill,1)+(Math.random()-.5)*(1-skill);agent.y+=dy*Math.min(.025*state.speed*skill,1)+(Math.random()-.5)*(1-skill);els.agent.style.left=agent.x+'%';els.agent.style.top=agent.y+'%';els.cursor.style.left=(23+agent.x*.48)+'%';els.cursor.style.top=(28+agent.y*.38)+'%';if(d<5||episodeTimer>7000){const won=d<5;state.episode++;state.reward=Math.max(0,Math.min(.9999,state.reward+(won?.002:-.006)+(Math.random()-.35)*.002));state.success=Math.min(98,state.success+(won?.018:-.045));state.steps=Math.max(4,state.steps+(won?-.006:.03));state.history.push(state.success/100);state.history.shift();$('episode').textContent=state.episode.toLocaleString();$('deltaEpisode').textContent=`+${state.episode-20148}`;$('reward').textContent=state.reward.toFixed(4);$('success').textContent=state.success.toFixed(1)+'%';$('steps').textContent=state.steps.toFixed(1);log(won?'✓ Target clicked · reward +1.0':'× Timeout · reward −0.5');episodeTimer=0;resetWorld();drawChart()}}
function loop(t){const dt=Math.min(t-last,50);last=t;step(dt);drawBrain(t);if(Math.floor(t/350)%5===0){$('spikeRate').textContent=(10+Math.random()*8).toFixed(1)+'K';$('activeNodes').textContent=Math.floor(3500+Math.random()*1600).toLocaleString()}requestAnimationFrame(loop)}
$('toggle').onclick=()=>{state.running=!state.running;$('toggle').innerHTML=state.running?'Ⅱ&nbsp;&nbsp; PAUSE TRAINING':'▶&nbsp;&nbsp; RESUME TRAINING';$('statusText').textContent=state.running?'TRAINING LIVE':'TRAINING PAUSED'};
$('reset').onclick=()=>{state.episode=20148;state.reward=.7488;state.success=72.4;state.steps=18.6;episodeTimer=0;resetWorld();log('Manual checkpoint restore')};
$('speed').oninput=e=>{state.speed=+e.target.value;$('speedOut').textContent=state.speed+'×'};
addEventListener('resize',()=>{initBrain();drawChart()});initBrain();drawChart();resetWorld();requestAnimationFrame(loop);
