const $=id=>document.getElementById(id),ctx=$('market').getContext('2d'),bctx=$('brain').getContext('2d');
const state={running:true,speed:4,episode:1,step:0,price:100,cash:10000,shares:0,equity:10000,peak:10000,reward:0,lastReward:0,vol:.016,regime:'CALM',bars:[],trades:[],halted:false,decision:{action:1,confidence:[.2,.6,.2],active:[]}};
const worker=new Worker('snn-worker.js'),actions=['BUY','HOLD','SELL'];let timer,brainNodes=[];
function seeded(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}let rand=seeded(42);
function normal(){return Math.sqrt(-2*Math.log(Math.max(rand(),1e-9)))*Math.cos(2*Math.PI*rand())}
function reset(){state.episode++;state.step=0;state.price=100;state.cash=10000;state.shares=0;state.equity=10000;state.peak=10000;state.reward=0;state.lastReward=0;state.halted=false;state.bars=[];state.trades=[];rand=seeded(state.episode*977);$('riskState').textContent='ARMED';$('riskState').style.color='';worker.postMessage({type:'init',seed:state.episode*977});for(let i=0;i<70;i++)marketStep(false);log('New deterministic episode #'+state.episode)}
function features(){const closes=state.bars.map(b=>b.c),n=closes.length,ret=k=>n>k?Math.tanh((closes[n-1]/closes[n-1-k]-1)*35):0;const mom=ret(8),short=ret(2),dd=1-state.equity/state.peak,pos=state.shares*state.price/state.equity;return[.5+short/2,.5+mom/2,Math.min(1,state.vol*20),Math.min(1,dd*20),Math.min(1,pos*2),.5+Math.sin(state.step/24)/2]}
function marketStep(decide=true){if(state.halted)return;state.step++;if(state.step%120===0){const r=rand();state.regime=r<.28?'BEAR':r<.62?'CALM':'BULL';$('regime').textContent=state.regime}const drift=state.regime==='BULL'?.00035:state.regime==='BEAR'?-.00038:.00005,sigma=state.vol/Math.sqrt(390);const o=state.price,c=o*Math.exp(drift+sigma*normal()),spread=Math.abs(sigma*normal())*o;state.price=c;state.bars.push({o,h:Math.max(o,c)+spread,l:Math.min(o,c)-spread,c});if(state.bars.length>95)state.bars.shift();const prev=state.equity;state.equity=state.cash+state.shares*c;state.peak=Math.max(state.peak,state.equity);const dd=(state.peak-state.equity)/state.peak;state.lastReward=(state.equity-prev)/10000-dd*.015;state.reward+=state.lastReward;if(dd>=.05){liquidate('DRAWDOWN LIMIT');state.halted=true;$('riskState').textContent='HALTED';$('riskState').style.color='var(--red)';log('RISK GATE: drawdown limit reached')}if(decide)worker.postMessage({type:'step',features:features(),reward:state.lastReward});render()}
function execute(action,confidence){if(state.halted)return;const target=[.5,state.shares*state.price/state.equity,0][action],current=state.shares*state.price/state.equity;if(Math.abs(target-current)<.08)return;const targetValue=state.equity*target,deltaShares=Math.trunc((targetValue-state.shares*state.price)/state.price);if(!deltaShares)return;const notional=Math.abs(deltaShares)*state.price,cost=notional*.0008;state.cash-=deltaShares*state.price+cost;state.shares+=deltaShares;state.trades.push({i:state.bars.length-1,action,price:state.price});log(actions[action]+' '+Math.abs(deltaShares)+' @ $'+state.price.toFixed(2)+' · '+(confidence*100).toFixed(0)+'%')}
function liquidate(reason){if(!state.shares)return;state.cash+=state.shares*state.price-Math.abs(state.shares)*state.price*.0008;log('SELL '+state.shares+' · '+reason);state.shares=0}
worker.onmessage=e=>{if(e.data.type==='ready'){$('engine').textContent=e.data.engine;brainNodes=Array.from({length:96},(_,i)=>({x:rand(),y:rand(),p:i}));return}state.decision=e.data;$('action').textContent=actions[e.data.action];$('spikeRate').textContent=(e.data.total*62.5).toFixed(0)+' spikes/s';['buyBar','holdBar','sellBar'].forEach((id,i)=>$(id).style.height=(8+e.data.confidence[i]*90)+'%');execute(e.data.action,e.data.confidence[e.data.action])}
function log(text){const p=document.createElement('p');p.innerHTML='<time>'+new Date().toISOString().slice(11,19)+'</time>'+text;$('orders').prepend(p);while($('orders').children.length>18)$('orders').lastChild.remove()}
function resize(c,cx){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);c.width=r.width*d;c.height=r.height*d;cx.setTransform(d,0,0,d,0,0)}
function drawMarket(){resize($('market'),ctx);const {width:w,height:h}=$('market').getBoundingClientRect(),bars=state.bars;if(!bars.length)return;const hi=Math.max(...bars.map(x=>x.h)),lo=Math.min(...bars.map(x=>x.l)),x=i=>(i+.5)*w/bars.length,y=p=>20+(hi-p)/(hi-lo||1)*(h-54);ctx.strokeStyle='#1b2025';ctx.lineWidth=1;for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(0,i*h/5);ctx.lineTo(w,i*h/5);ctx.stroke()}bars.forEach((b,i)=>{const color=b.c>=b.o?'#c7ff3d':'#ff5f68',xx=x(i),bw=Math.max(2,w/bars.length*.55);ctx.strokeStyle=color;ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(xx,y(b.h));ctx.lineTo(xx,y(b.l));ctx.stroke();ctx.fillRect(xx-bw/2,Math.min(y(b.o),y(b.c)),bw,Math.max(1,Math.abs(y(b.o)-y(b.c))))});state.trades.slice(-20).forEach(t=>{ctx.fillStyle=t.action===0?'#62d9ff':'#ffb84a';ctx.beginPath();ctx.arc(x(Math.max(0,bars.length-(state.step-t.i))),y(t.price),3,0,7);ctx.fill()})}
function drawBrain(){resize($('brain'),bctx);const {width:w,height:h}=$('brain').getBoundingClientRect();bctx.strokeStyle='#24313a';brainNodes.forEach((n,i)=>{const q=brainNodes[(i*13+17)%brainNodes.length];bctx.beginPath();bctx.moveTo(n.x*w,n.y*h);bctx.lineTo(q.x*w,q.y*h);bctx.stroke()});const active=new Set(state.decision.active.map(x=>x%96));brainNodes.forEach((n,i)=>{bctx.fillStyle=active.has(i)?'#c7ff3d':'#43606d';bctx.beginPath();bctx.arc(n.x*w,n.y*h,active.has(i)?2.5:1,0,7);bctx.fill()})}
function render(){state.equity=state.cash+state.shares*state.price;const dd=(state.peak-state.equity)/state.peak*100,pos=state.equity?state.shares*state.price/state.equity*100:0;$('lastPrice').textContent='$'+state.price.toFixed(2);$('equity').textContent='$'+state.equity.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});$('pnl').textContent='P&L '+(state.equity>=10000?'+':'')+'$'+(state.equity-10000).toFixed(2);$('drawdown').textContent=dd.toFixed(2)+'%';$('position').textContent=pos.toFixed(0)+'%';$('shares').textContent=state.shares+' shares';$('reward').textContent=state.reward.toFixed(3);$('episode').textContent=state.episode;$('step').textContent='STEP '+state.step+' / 480';$('ddProgress').value=dd;$('exposureProgress').value=Math.abs(pos);drawMarket();drawBrain()}
function schedule(){clearInterval(timer);timer=setInterval(()=>{if(state.running)for(let i=0;i<state.speed;i++)marketStep()},220)}
$('toggle').onclick=()=>{state.running=!state.running;$('toggle').innerHTML=state.running?'Ⅱ&nbsp;&nbsp; PAUSE':'▶&nbsp;&nbsp; RESUME';$('runStatus').textContent=state.running?'PAPER TRAINING LIVE':'TRAINING PAUSED'};$('reset').onclick=reset;$('speed').oninput=e=>{$('speedOut').textContent=(state.speed=+e.target.value)+'×'};$('volatility').onchange=e=>state.vol=+e.target.value;addEventListener('resize',render);reset();schedule();
